server:
  port: 9001
  servlet:
    context-path: /hrm
spring:
  application:
    name: hrm
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.60.14:3306/hrm?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: stest1
    password: P@ssw0rd1
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace